language: erlang
otp_release:
  - 21.3
  - 22.3
  - 23.0
install:
  - make
  - ./rebar3 update
script:
  - make format
  - make test
  - make proper
  - make coverage
  - ./rebar3 as test coveralls send
  - make lint
  - make xref
  - make dialyzer
  - make docs
sudo: required
dist: trusty
